### ISSUE TITLE
Import `kci-easy` as a new deployment type

### ISSUE THREAD

**Issue by pawiecz** [kernelci/kernelci-deploy#149]
[`kci-easy`](https://github.com/nuclearcat/kci-easy) is a tool created to simplify deployment of a local KernelCI system instance.

It could be leveraged as a development/evaluation environment for the new system.

Potential names for its subdirectory within `-deploy` repo were suggested on IRC:
- "localinstall"
- "local"

**Comment by nuclearcat** [comment]
I would vote for localinstall, local is too generic.

**Comment by pawiecz** [comment]
I agree just "local" might seem too generic without any context. Although I do believe it should be fine in the context of `-deploy` repo, let's drop it in favor of another one.

Currently we've got two subdirectories for deploying KernelCI onto Kubernetes clusters ("k8s" and "kubernetes" just for Azure).

@nuclearcat do you think that it would make sense to store `kci-easy` in a "docker-compose" directory to reflect base tech required for this deployment type? Then we could still reuse "localinstall" for running KernelCI system components without any middleware (just as system services).

I created #150 to import your code here (with some adjustments not merged in the source repo yet) under "localinstall" but will happily `git mv` it and amend that PR if we agree on other naming scheme.
