### ISSUE TITLE
patch 0001-selftests-add-missing-in-lib.mk.patch temporary moved to home directory from patches/linux/staging-next/

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-deploy#49]
patches: patches/linux/staging-next
Applying patch: patches/linux/staging-next/0001-selftests-add-missing-in-lib.mk.patch
error: patch failed: tools/testing/selftests/lib.mk:20
error: tools/testing/selftests/lib.mk: patch does not apply
hint: Use 'git am --show-current-patch=diff' to see the failed patch
WARNING: Failed to apply patch

**Comment by gctucker** [comment]
But that patch isn't under source control, right?  I think we can just delete the patch and close this issue.

**Comment by nuclearcat** [comment]
It isn't, but since someone spent time making it(its yours), better i make sure if it is needed or not.
It is either implemented in upstream, or just need update.

**Comment by gctucker** [comment]
OK I didn't know it was mine, would have helped if you told me ;)  I'll delete it and close this issue.

**Comment by gctucker** [comment]
Yes that patch has since been applied to Shuah's fixed branch.
